### ISSUE TITLE
Disable jQuery linting error

### ISSUE THREAD

**Issue by stramel** [AtomLinter/linter-bootlint#1]
Not every project uses jQuery even when using bootstrap. It is not a required dependency for the styling of a page.

Along those lines, also, it would be nice to not get errors about not being a complete HTML document when using templating.

**Comment by cvrebert** [comment]
You can disable any particular lint checker in Bootlint using the `disabledIds` argument. Does `linter-bootlint` offer a way to set that?

**Comment by stramel** [comment]
Should be able to do this with the referenced PR. Flags is a comma separated list to disable certain checks.
