### ISSUE TITLE
The linter binary 'bootlint' cannot be found.

### ISSUE THREAD

**Issue by DJviolin** [AtomLinter/linter-bootlint#10]
"The linter binary 'bootlint' cannot be found.
Linting has been halted. Please install the linter binary or disable the linter plugin depending on it. Make sure to reload Atom to detect changes"

Can you tell me what causing this?

**Comment by asolfre** [comment]
Same here on W7.

atom:1.0.2
linter: 1.2.4
linter-bootlint: 0.0.6

**Comment by Arcanemagus** [comment]
Marking this as closed, if this linter is ever going to be working again it will need a re-write which would change how this worked anyway.
