### ISSUE TITLE
Failed to load snippets from 

### ISSUE THREAD

**Issue by lorenzovcr** [AtomLinter/linter-bootlint#113]
When I tried to install this package I got this error inside of Atom.

`/components-button_group.cson: Duplicate key 'Button group - Bootstrap 4'`
 `/components-pagination.cson'`

**Comment by Arcanemagus** [comment]
Are you _sure_ you are installing this package? None of what you posted is related to this package.

**Comment by lorenzovcr** [comment]
Sorry for the confusion I just looked into it and it was my error. 

Thanks everyone!
