### ISSUE TITLE
Getting the following message: [Linter] Error running Bootlint

### ISSUE THREAD

**Issue by stacyrch2019** [AtomLinter/linter-bootlint#206]
I get **[Linter] Error running Bootlint** whenever I do anything in Atom now. I can't type anything without this message appearing. 

Started day before yesterday and uninstall/reinstall did nothing to mitigate this. Google fu is failing me--seems like no one else has had this specific problem. Has anyone had this problem?

**Comment by stacyrch2019** [comment]
I took care of this by uninstalling Atom's linter-bootlint.

**Comment by Spodeian** [comment]
I am also getting this error, it states Bootlint needs to run as root or suid (admin).
