### ISSUE TITLE
BufferedProcessError: Failed to spawn command 

### ISSUE THREAD

**Issue by E-SHADOW** [AtomLinter/linter-bootlint#38]
How i can fix this problem ?

![2016-03-02_22-31-44](https://cloud.githubusercontent.com/assets/15945528/13474472/d1ba9694-e0c6-11e5-8351-485466f8679e.jpg)

And thank you so much :)

**Comment by Arcanemagus** [comment]
Does the file exist? Atom seems to (pretty rarely) have issues installing package dependencies properly.

**Comment by E-SHADOW** [comment]
So ! What can i do to fix this problem ?

**Comment by Arcanemagus** [comment]
First thing I would try is just uninstalling and re-installing the package.

**Comment by E-SHADOW** [comment]
Ok i will do that now..

**Comment by E-SHADOW** [comment]
Done and done update also.. but i still have the same problem

**Comment by E-SHADOW** [comment]
You can help me by team viewer ?

**Comment by Arcanemagus** [comment]
If you want, join Atom's slack and send me a direct message.

**Comment by woofiewilly** [comment]
I also have the same issue. I'd like to know how to resolve it. 

I notice for some reason in the filepath it searches it removes the '\' before the folders that start with '.' 

I tried overriding this by inputting the exact same path (but with correct slashes) into the executable path setting, but it still does the same thing.

**Comment by Arcanemagus** [comment]
@woofiewilly If you notice the path is correct in the full error, it's just a side effect of Atom's notifications that those aren't showing in the title as well (possibly need to be escaped there or something?)

Have you tried reinstalling `linter-bootlint`? If you run `npm list --depth=0` in the package directory what do you see?

**Comment by woofiewilly** [comment]
I'm on Windows. How can I run those commands without the terminal?

**Comment by Arcanemagus** [comment]
Simple open up a PowerShell session, or Command Prompt. Although that command assumes you have Node.js installed which I realize isn't strictly a necessity to run this.

**Comment by MattOxberry** [comment]
This issue is still present. I have uninstalled and reinstalled a number of times and it is still throwing the same error.

**Comment by Arcanemagus** [comment]
@MattOxberry can you answer the questions asked in the rest of this thread?

* Does the file actually exist?
* If you have Node.js installed, what does `npm list --depth=0` show?

**Comment by MattOxberry** [comment]
node_modal.bin does not exist.

I do not have Node.js installed.

**Comment by Arcanemagus** [comment]
"node_modal.bin" _shouldn't_ exist... does `node_modules\.bin\bootlint` exist?

**Comment by MattOxberry** [comment]
That does exist yes. The error confused me because it showed node_modules.bin\ 

But yes I do have node_modules\.bin\bootlint

**Comment by Arcanemagus** [comment]
What OS are you on?

**Comment by MattOxberry** [comment]
Windows 10

**Comment by Arcanemagus** [comment]
Hmmm, it's possible that `bootlint` itself assumes that Node.js is installed, if you install that (making no other changes) does it start working for you?

**Comment by MattOxberry** [comment]
Working after installing Node.js. Thanks for the help.

**Comment by Arcanemagus** [comment]
Interesting, glad to hear that fixed it.

@woofiewilly and @E-SHADOW if you install Node.js on your system does it resolve this for you? It seems `bootlint` isn't just assuming it's running within node and working fine within Atom's environment and it actually _needs_ Node.js installed.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response. Please file a new issue if you run into this again.
