### ISSUE TITLE
How to use flags in Atom Settings?

### ISSUE THREAD

**Issue by JojoJohnDoe** [AtomLinter/linter-bootlint#40]
Hey i got a little question.

I want to disable certain lint checks using the settings "Flags"-Field. 

How exactly should this look like? Tried "-d E001" & "E001" but without succss.

Thanks!

**Comment by Arcanemagus** [comment]
It should just be `E001`, are you on v1.0.2? It was broken before that version unfortunately.

**Comment by Arcanemagus** [comment]
Did updating the plugin fix this for you?

**Comment by JojoJohnDoe** [comment]
Yes thank you. :)
-- 
Johannes Karow
Sent with Airmail

**Comment by Arcanemagus** [comment]
Awesome, glad to hear it.
