### ISSUE TITLE
Process Execution Timed Out

### ISSUE THREAD

**Issue by cjduncana** [AtomLinter/linter-bootlint#44]
This appeared while coding, and I could not figure out what to do about it. It seems that AtomLinter/linter-flake8#169, AtomLinter/linter-proselint#4, and AtomLinter/linter-phpcs#114 also have a similar problem.

![selection_006](https://cloud.githubusercontent.com/assets/1977082/14333505/a4a26f38-fc14-11e5-92a1-a3c92314676b.png)

**Comment by rgreenjr** [comment]
I've been getting this error the last couple of days too.
