### ISSUE TITLE
Error: spawn ..... ENOENT

### ISSUE THREAD

**Issue by OmriBromberg** [AtomLinter/linter-bootlint#48]
https://gyazo.com/9669031f0b1c8be200951ef851442f81

```                                    
Error: spawn C:\Users\Omri.atom\packages\linter-bootlint\node_modules.bin\bootlint ENOENT
Error: spawn C:\Users\Omri\.atom\packages\linter-bootlint\node_modules\.bin\bootlint ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickDomainCallback (node.js:420:17)
```

**Comment by kumiao** [comment]
I have the same proplem！！！

**Comment by Arcanemagus** [comment]
Does that file exist? `apm` sometimes fails to properly install all of a package's dependencies.

**Comment by Arcanemagus** [comment]
Ah, looks like this is actually another case of https://github.com/steelbrain/atom-linter/issues/129.

**Comment by A----** [comment]
I had the same issue today, and yes, the file existed. I also did a `npm install --production` in the `linter-bootlint` directory to no avail.

Setting `C:\[…]\.atom\packages\linter-bootlint\node_modules\.bin\bootlint.cmd` (note the `.cmd`) removed the error. In one of my files, a warning got reported but I'm pretty sure that there should have been more. That's probably a different issue entirely though.

**Comment by Arcanemagus** [comment]
Yea, if you check the linked issue apparently the newest version of a helper library used by the `atom-linter` helper library appears to have broken things on Windows, @steelbrain is working on a fix.

**Comment by Arcanemagus** [comment]
Btw, a fixed version of `sb-exec` has been released, unfortunately the simplest way to force the update is to just re-install _all_ of your `linter-____` packages.

If you are still experiencing problems after doing that (and restarting Atom) please file a new issue.

**Comment by A----** [comment]
Works now with default parameters! :+1:
