### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by PAINTandCODE** [AtomLinter/linter-bootlint#74]
The instant I open a local file in Atom to edit, I get this error along with an additional copy of the error with every change to the file I make.

![screen shot 2016-08-21 at 12 52 22 pm](https://cloud.githubusercontent.com/assets/3489188/17839485/3a0be6e0-679e-11e6-95bc-5ba8b558fd0f.png)

**Comment by Arcanemagus** [comment]
If I remember correctly `bootlint` requires Node.js to be installed on your system, is that available?

**Comment by suMiaow** [comment]
Bootlint requires `node`, but not `nodejs`, so you should copy `nodejs` to `node`.

**Comment by Arcanemagus** [comment]
@suMiaow That... makes no sense 😕. When you install Node.js, you should get a `node` _binary_ installed on your system (as well as things like `npm`).

Maybe your specific Linux distro is non-standard and installs a `nodejs` binary?

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response from @PAINTandCODE.
